# Generated by Django 5.0 on 2026-05-03 22:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apoderado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("dni", models.CharField(max_length=8)),
                ("celular", models.CharField(max_length=9)),
                ("direccion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ciclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Distrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=70)),
                ("direccion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido_paterno", models.CharField(max_length=70)),
                ("apellido_materno", models.CharField(max_length=70)),
                ("nombres", models.CharField(max_length=70)),
                (
                    "dni",
                    models.CharField(
                        max_length=8,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{8}$", "El DNI debe tener 8 digitos"
                            )
                        ],
                    ),
                ),
                ("celular", models.CharField(max_length=9)),
                ("fecha_nacimiento", models.DateField()),
                ("direccion", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=10,
                    ),
                ),
                (
                    "apoderado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.apoderado",
                    ),
                ),
                (
                    "distrito",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.distrito",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.sede"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormacionAdicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estudio_previo", models.BooleanField()),
                ("tipo_estudio", models.CharField(max_length=20)),
                ("academia_anterior", models.CharField(max_length=100)),
                ("carrera_interes", models.CharField(max_length=100)),
                (
                    "segunda_carrera",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "alumno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="web.alumno"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstitucionEducativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "distrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.distrito"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormacionAcademica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_institucion", models.CharField(max_length=20)),
                (
                    "alumno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="web.alumno"
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.institucioneducativa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_matricula", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("pendiente", "Pendiente"), ("pagado", "Pagado")],
                        max_length=20,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.alumno"
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.ciclo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("secretaria", "Secretaria"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.sede"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField(default=django.utils.timezone.now)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("yape", "Yape"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.matricula"
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.perfil"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="matricula",
            name="registrado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.perfil"
            ),
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.departamento",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="distrito",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.provincia"
            ),
        ),
        migrations.AddField(
            model_name="ciclo",
            name="sede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.sede"
            ),
        ),
    ]
