# Generated by Django 5.0 on 2026-03-17 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('celular', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=70)),
                ('apellido_materno', models.CharField(max_length=70)),
                ('nombres', models.CharField(max_length=70)),
                ('dni', models.CharField(max_length=8)),
                ('celular', models.CharField(max_length=9)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.apoderado')),
                ('Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.alumno')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('secretaria', 'Secretaria')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.matricula')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='ciclo',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sede'),
        ),
    ]
