# Generated by Django 5.0 on 2026-03-22 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='Sede',
            new_name='sede',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='Alumno',
            new_name='alumno',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_institucion', models.CharField(max_length=20)),
                ('nombre_ie', models.CharField(max_length=100)),
                ('distrito_ie', models.CharField(max_length=50)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio_previo', models.BooleanField()),
                ('tipo_estudio', models.CharField(max_length=20)),
                ('academia_anterior', models.CharField(max_length=100)),
                ('carrera_interes', models.CharField(max_length=100)),
                ('segunda_carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.alumno')),
            ],
        ),
    ]
