# Generated by Django 5.0 on 2026-05-03 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacionacademica',
            name='nombre_ie',
        ),
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.distrito')),
            ],
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.institucioneducativa'),
        ),
    ]
