# Generated by Django 5.0 on 2026-05-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
