# Generated by Django 5.0 on 2026-05-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="apoderado",
            name="dni",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
