# Generated by Django 5.0 on 2026-05-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_formacionacademica_nombre_ie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacionacademica',
            name='distrito_ie',
        ),
    ]
