# Generated by Django 5.0 on 2026-05-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_sede_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='apoderado',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
