# Generated by Django 5.0 on 2026-04-25 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_sede_alumno_sede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='registrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.perfil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('transferencia', 'Transferencia')], max_length=20),
        ),
    ]
