# Generated by Django 5.0 on 2026-04-29 16:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_matricula_registrado_por_alter_matricula_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='perfil',
            new_name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='estado',
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apoderado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.apoderado'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'El DNI debe tener 8 digitos')]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
