# Generated by Django 5.0 on 2026-05-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_pago_apoderado'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='tipo_ie',
            field=models.CharField(blank=True, choices=[('Nacional', 'Nacional'), ('Particular', 'Particular')], default='', max_length=20),
        ),
    ]
