# Generated by Django 5.0 on 2026-05-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_add_tipo_ie_to_institucion_educativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='proximo_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
