# Generated by Django 5.0 on 2026-05-18 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_add_proximo_pago_to_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=10),
        ),
        migrations.CreateModel(
            name='DesactivacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('retiro_voluntario', 'Retiro voluntario'), ('deuda_pendiente', 'Deuda pendiente'), ('inasistencia', 'Inasistencia prolongada'), ('expulsion', 'Expulsión'), ('otro', 'Otro')], max_length=30)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desactivaciones', to='web.alumno')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.perfil')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
