# Generated by Django 5.0 on 2026-05-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_add_bloqueado_state_and_desactivacion_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_desactivacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
